# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DBVoiceTransfer' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
   pod 'Toast', '~> 4.0.0'

   target 'DBBVoiceTransfer' do
#    inherit! :none
    pod 'DBCommonLib', '~> 2.2.3'

   end

   
  # Pods for DBVoiceTransfer

  target 'DBVoiceTransferTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DBVoiceTransferUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
